[default]
log_level = "info"
log_to_stderr = true
log_max_megabytes = 100
log_backups = 2
max_idle_conns = 100
dial_timeout = 30
dns_ttl = 1800
prefer_ipv6 = false
reject_intranet = false
allow_empty_sni = true

[[http2]]
listen = ":443"
server_name = ["example.org"]
keyfile = "example.org.key"
certfile = "example.org.cer/fullchain.cer"
forward_allow_legacy_https = false
proxy_pass = "file:///var/www/html"
enable_pprof = true
enable_metrics = true
